### ISSUE TITLE
add an "on nth call" assertion

### ISSUE THREAD

**Issue by joelmukuthu** [unexpectedjs/unexpected-sinon#16]
Something like this:
```js
expect(spy, 'on first call', 'was called with', someArgument);
```
Or alternatively define the current assertions on the `spyCall` type. 
Is this kind of functionality already there?

**Comment by papandreou** [comment]
Would this be sufficient?

```js
expect(spy, 'to have calls satisfying', {
    0: { args: [ someArgument ] }
});
```

Personally I'd rather spell out all the calls like this so that I'm sure that no extraneous calls slip through:

```js
expect(spy, 'to have calls satisfying', function () {
    spy(someArgument);
    spy(123);
    spy(456);
});
```

If that doesn't cover your use case, could you please write a few words about why you're only interested in a particular call? The other day we discussed a `to have some calls satisfying` variant, but there wasn't really that much interest when it came down to it.

**Comment by joelmukuthu** [comment]
I'm interested in a particular call because I'd like to test the various calls in separate unit tests. My spy could be called a couple of times with different arguments each time and I'd like to test each call in an individual unit test. This could be achieved with the syntax you suggested in your first example but spelling it out (`on first call`, `on second call` etc) would be more readable I think.

**Comment by papandreou** [comment]
There's also sinon's built-in `getCall` method that returns a spy call object, which has a `to satisfy` implementation in unexpected-sinon (the RHS object can also include `returnValue`, `thisObject`, `threw` etc.):

```js
expect(spy.getCall(1), 'to satisfy', { args: [ 123 ] });
```

That'll output something like this when it fails:

```
expected spy0( 456 ) at Object.<anonymous> (myFile.js:5:1) to satisfy { args: [ 123 ] }

spy0(
  456 // should equal 123
) at Object.<anonymous> (myFile.js:5:1)
```

So it won't include the other calls as "context" in the diff, but it might still do the trick?

**Comment by joelmukuthu** [comment]
Aah, I did try to use sinon's `getCall` method but I was still trying them with the assertions built for the `spy` type (`was called with` etc). Perhaps we should update the documention and add `to satisfy` for `spyCall` type?

**Comment by papandreou** [comment]
Yeah, that would be a good idea. Until now the `spyCall` type has mostly been an implementation detail, but this is proof that it's useful on its own :)

PR very welcome.

**Comment by joelmukuthu** [comment]
Closing this in favour of https://github.com/unexpectedjs/unexpected-sinon/issues/20

**Comment by papandreou** [comment]
@PabloSichert brought up an idea similar to this one today, mostly because he would like to be able to assert on the last call made to the spy without worrying about how many calls were made in total.

We talked about it for a bit and didn't really like any of these syntaxes:

```js
expect(spy, 'on first call', 'was called with', someArgument);
expect(spy, 'to have nth call satisfying', 2, [ 123 ]);
expect(spy, 'to have nth call satisfying', -2, [ 123 ]); // second last
```

However, as long as the use case is getting to the last couple of calls, we could also consider to spell out the call numbers fully:

```js
expect(spy, 'to have second call satisfying', [ 123 ]);
expect(spy, 'to have last call satisfying', [ 123 ]);
expect(spy, 'to have second last call satisfying', [ 123 ]);
```

Turns out sinon itself defines `spy.firstCall`, `spy.secondCall`, and even `spy.thirdCall`, so it's not completely unheard of.

@joelmukuthu @sunesimonsen, what do you think?

**Comment by joelmukuthu** [comment]
I'm all for it and I like the wording of the assertions, much better than what I had originally suggested. I'd suggest we only support the ones supported by sinon though i.e. `spy.firstCall`, `spy.secondCall`, `spy.thirdCall` and `spy.lastCall`. For the others like "second last call" I think [`<spyCall> to satisfy <any>`](http://unexpected.js.org/unexpected-sinon/assertions/spyCall/to-satisfy/) is sufficient.

**Comment by papandreou** [comment]
@joelmukuthu Thanks for chiming in :)

> For the others like "second last call" I think <spyCall> to satisfy <any> is sufficient.

Unfortunately `spy.getCall(<number>)` doesn't support negative indices, so for the second last call you'd have to do something like `expect(spy.calls[spy.calls.length - 2], 'to satisfy', ...);`, and then `to have second last call satisfying` reads much nice IMO. We could probably PR that to sinon, though.

**Comment by joelmukuthu** [comment]
It does read better :) Though I'm more in favour of upstreaming it to sinon first and then implementing it here if they approve of it

**Comment by sunesimonsen** [comment]
I'm okay with also including second last call, just don't take it too far.
